---
# Template configuration files for time

- name: template is copied
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  become: true
  loop: "{{ time_templates_copy }}"
  when: time_copy_templates
